import { Link } from 'react-router-dom'
import { useProgress } from '../state/ProgressContext'
import { useLanguage } from '../i18n/LanguageContext'
export default function Home(){
 const {progress}=useProgress(); const {lang}=useLanguage(); const es=lang==='es'; const started=Object.keys(progress.visited).length>0
 return <div className="home page">
  <section className="home-hero">
   <div className="hero-copy"><div className="kicker"><span>{es?'SISTEMA DE APRENDIZAJE PROFESIONAL':'PRODUCTION LEARNING SYSTEM'}</span><i/>AIR POWER SERVICES</div><h1><span>ESG</span> ESSENTIALS</h1><p className="hero-sub">{es?'Medio ambiente, dimensión social y gobernanza para Air Power Services':'Environmental, Social & Governance for Air Power Services'}</p><p className="hero-tag">{es?'De los principios a mejores decisiones empresariales':'From Principles to Better Business Decisions'}</p>
   <div className="hero-actions"><Link className="button primary" to={started?progress.lastRoute||'/modules':'/module/00/opening'}>{started?(es?'Continuar curso':'Continue course'):(es?'Iniciar curso':'Start course')} <span aria-hidden="true">→</span></Link><Link className="button ghost" to="/overview">{es?'Explorar el curso':'Explore the course'}</Link></div>
   <p className="local-note">{es?'El progreso se guarda localmente en este dispositivo. No se necesita cuenta ni se solicitan datos personales.':'Progress is stored locally on this device. No account or personal data required.'}</p></div>
   <figure className="home-cinematic"><img src="./images/home-hero.webp" alt={es?'Un equipo multidisciplinar del sector aeroespacial examina evidencias interconectadas de ingeniería y decisión en un entorno técnico luminoso.':'A multidisciplinary aerospace programme team examining interconnected engineering and decision evidence in a bright technical environment.'} fetchPriority="high"/><figcaption>{es?'La evidencia se vuelve útil cuando las personas pueden conectarla con la autoridad, las consecuencias y la acción.':'Evidence becomes useful when people can connect it to authority, consequence and action.'}</figcaption></figure>
  </section>
  <section className="course-facts" aria-label={es?'Datos del curso':'Course facts'}><div><strong>10 {es?'módulos':'modules'}</strong><span>{es?'Un recorrido de aprendizaje conectado':'A connected learning journey'}</span></div><div><strong>7 h 39 min</strong><span>{es?'Diseñado para un aprendizaje profesional centrado':'Designed for focused professional learning'}</span></div><div><strong>E + S + G</strong><span>{es?'Medio ambiente, dimensión social y gobernanza, de forma integrada':'Environmental, social and governance together'}</span></div><div><strong>{es?'Nivel básico':'Foundation level'}</strong><span>{es?'No se requieren conocimientos previos de ESG':'No previous ESG expertise required'}</span></div></section>
  <section className="home-intro"><div><div className="eyebrow">{es?'POR QUÉ ESTE CURSO':'WHY THIS COURSE'}</div><h2>{es?'Observa la decisión completa, no solo la métrica visible.':'See the whole decision—not only the visible metric.'}</h2></div><p>{es?'Aprende a conectar dependencias ambientales, impactos sobre las personas, calidad de la evidencia, autoridad y consecuencias empresariales. El curso avanza desde los principios básicos hasta una simulación de decisión gobernada en un contexto de Air Power Services.':'Learn to connect environmental dependencies, impacts on people, evidence quality, authority and business consequences. The course builds from first principles to a governed Air Power Services decision simulation.'}</p></section>
 </div>
}
