import { glossary } from '../data/course'
import sources00 from '../../content/module-00/SOURCES.md?raw'
import sources09 from '../../content/module-09/SOURCES.md?raw'
import { moduleContent } from '../data/moduleContent'
import Markdown from '../components/Markdown'
import { useProgress } from '../state/ProgressContext'
export function Glossary(){return <div className="page narrow"><div className="eyebrow">SHARED LANGUAGE</div><h1>Glossary</h1><p className="lead">Terms carry different meanings. These definitions preserve the distinctions used throughout the course.</p><dl className="glossary">{glossary.map(([t,d])=><div key={t}><dt>{t}</dt><dd>{d}</dd></div>)}</dl></div>}
export function Sources(){return <div className="page narrow"><div className="eyebrow">EVIDENCE ARCHITECTURE</div><h1>Sources &amp; further reading</h1><p className="lead">Source notes remain close to the module they support. They establish traceability; they do not turn learning scenarios into real company claims.</p><div className="source-library"><Markdown source={sources00}/>{Object.values(moduleContent).map(m=><Markdown key={m.id} source={m.sources}/>)}<Markdown source={sources09}/></div></div>}
export function About(){return <div className="page narrow"><div className="eyebrow">ABOUT THIS EXPERIENCE</div><h1>Better questions. Better governed decisions.</h1><p className="lead">ESG Essentials is an educational course for Air Power Services contexts. Fictional learning scenarios are non-classified and are not actual supplier, policy or approval decisions.</p><div className="editorial-panel"><h2>Important boundary</h2><p>This course does not provide legal, financial, investment, technical-airworthiness or operational approval. It does not certify, qualify or accredit the learner. Follow applicable organizational procedures and accountable authorities in real decisions.</p></div></div>}
export function Progress(){const {progress,reset}=useProgress();return <div className="page narrow"><div className="eyebrow">LOCAL LEARNING STATE</div><h1>Learning progress</h1><div className="progress-summary"><strong>{progress.completedModules.length}/10</strong><p>Modules completed</p></div><p>Your state is stored only in this browser on this device. Resetting cannot be undone.</p><button className="button danger" onClick={()=>{if(window.confirm('Reset all learning progress on this device?'))reset()}}>Reset progress</button></div>}
