import { useState } from 'react'
import { resolveAttempt } from '../state/engines'
import { useProgress } from '../state/ProgressContext'

const questions=[
 {id:'Q-001',title:'Sustainability or ESG?',q:'An organization publishes workforce and emissions indicators but has no process for using them in decisions. Which statement is most accurate?',a:['Publishing ESG data proves the business model is sustainable.','ESG reporting and sustainability are identical.','The indicators may support ESG accountability, but publication alone does not prove sustainable performance.','Indicators have no value unless every effect is converted to money.'],c:2,r:'Data can support transparency and decision-making, but its value depends on boundaries, quality, interpretation and action.'},
 {id:'Q-002',title:'Connected dimensions',q:'A team changes to a lower-cost mineral supplier. The new source has uncertain water impacts, reports of recruitment fees and unclear sub-tier approval. What is the best first response?',a:['Classify it only as an environmental issue because minerals come from nature.','Classify it only as a social issue because recruitment fees affect workers.','Treat it as a connected E/S/G decision and investigate material evidence before approval.','Ignore ESG because the supplier meets the component specification.'],c:2,r:'Water/material impacts, worker conditions and approval/evidence controls are connected.'},
 {id:'Q-003',title:'Externality and consequence',q:'Which example best demonstrates how an externality can become a business consequence?',a:['Pollution affects a community, leading to operational restrictions, remediation cost and loss of trust.','A purchase order records the agreed unit price.','A manager approves a budget within delegated authority.','A component passes its specified inspection.'],c:0,r:'A consequence initially outside the transaction returns through restrictions, cost and stakeholder response.'},
 {id:'Q-004',title:'Governance',q:'Which evidence most strongly suggests that a public ESG commitment is governed rather than merely stated?',a:['The commitment uses ambitious language.','It has a defined boundary, accountable owner, resources, measures, controls and review route.','It appears prominently in external communications.','A rating provider has mentioned it.'],c:1,r:'Governance links intent to authority, evidence, action and accountability.'},
 {id:'Q-005',title:'Decision quality',q:'A team cannot quantify a potential community impact precisely. What is the most defensible action?',a:['Exclude it because only numerical evidence is valid.','Invent a conservative number so the matrix is complete.','State the uncertainty, gather proportionate qualitative and quantitative evidence, and define escalation.','Allow the most senior person to decide without documenting assumptions.'],c:2,r:'Evidence-conscious decisions do not confuse uncertainty with irrelevance or manufacture precision.'}
]
export default function Assessment(){
 const {progress,saveQuestion}=useProgress(); const [index,setIndex]=useState(0); const [choice,setChoice]=useState(null)
 const q=questions[index],saved=progress.questions[q.id]; const [result,setResult]=useState(saved||null)
 const submit=e=>{e.preventDefault();if(choice===null)return;const n=resolveAttempt(result,choice,q.c);const full={...n,module:'00'};setResult(full);saveQuestion(q.id,full)}
 const change=i=>{setIndex(i);setChoice(null);setResult(progress.questions[questions[i].id]||null)}
 return <section className="assessment" aria-labelledby="check-title"><div className="eyebrow">KNOWLEDGE CHECK · {index+1} / 5</div><h2 id="check-title">{q.title}</h2><p className="question">{q.q}</p>
  <form onSubmit={submit}><fieldset disabled={result?.completed}><legend className="sr-only">Choose one answer</legend>{q.a.map((a,i)=><label className={'answer '+(result?.reveal&&i===q.c?'correct':'')} key={a}><input type="radio" name={q.id} checked={choice===i} onChange={()=>setChoice(i)}/><span><b>{String.fromCharCode(65+i)}</b>{a}</span></label>)}</fieldset>
  {!result?.completed&&<button className="button primary" disabled={choice===null}>Submit response</button>}</form>
  {result&&<div tabIndex="-1" className={'feedback '+(result.correct?'positive':'caution')}><strong>{result.correct?'Evidence aligned':'Review the reasoning'}</strong><p>{result.correct?q.r:result.reveal?'The correct response is '+String.fromCharCode(65+q.c)+'. '+q.r:'This response misses part of the decision context. Review the options and try once more.'}</p>{!result.completed&&<button className="text-button" onClick={()=>{setChoice(null);setResult(result)}}>Retry question</button>}</div>}
  <div className="question-nav" aria-label="Question navigation">{questions.map((x,i)=><button key={x.id} className={(i===index?'current ':'')+(progress.questions[x.id]?.completed?'done':'')} onClick={()=>change(i)} aria-label={'Question '+(i+1)}>{i+1}</button>)}</div>
 </section>
}

