import { useState } from 'react'
import { resolveAttempt } from '../state/engines'
import { useProgress } from '../state/ProgressContext'
import { useLanguage } from '../i18n/LanguageContext'

const questionsEn=[
 {id:'Q-001',title:'Sustainability or ESG?',q:'An organization publishes workforce and emissions indicators but has no process for using them in decisions. Which statement is most accurate?',a:['Publishing ESG data proves the business model is sustainable.','ESG reporting and sustainability are identical.','The indicators may support ESG accountability, but publication alone does not prove sustainable performance.','Indicators have no value unless every effect is converted to money.'],c:2,r:'Data can support transparency and decision-making, but its value depends on boundaries, quality, interpretation and action.'},
 {id:'Q-002',title:'Connected dimensions',q:'A team changes to a lower-cost mineral supplier. The new source has uncertain water impacts, reports of recruitment fees and unclear sub-tier approval. What is the best first response?',a:['Classify it only as an environmental issue because minerals come from nature.','Classify it only as a social issue because recruitment fees affect workers.','Treat it as a connected E/S/G decision and investigate material evidence before approval.','Ignore ESG because the supplier meets the component specification.'],c:2,r:'Water/material impacts, worker conditions and approval/evidence controls are connected.'},
 {id:'Q-003',title:'Externality and consequence',q:'Which example best demonstrates how an externality can become a business consequence?',a:['Pollution affects a community, leading to operational restrictions, remediation cost and loss of trust.','A purchase order records the agreed unit price.','A manager approves a budget within delegated authority.','A component passes its specified inspection.'],c:0,r:'A consequence initially outside the transaction returns through restrictions, cost and stakeholder response.'},
 {id:'Q-004',title:'Governance',q:'Which evidence most strongly suggests that a public ESG commitment is governed rather than merely stated?',a:['The commitment uses ambitious language.','It has a defined boundary, accountable owner, resources, measures, controls and review route.','It appears prominently in external communications.','A rating provider has mentioned it.'],c:1,r:'Governance links intent to authority, evidence, action and accountability.'},
 {id:'Q-005',title:'Decision quality',q:'A team cannot quantify a potential community impact precisely. What is the most defensible action?',a:['Exclude it because only numerical evidence is valid.','Invent a conservative number so the matrix is complete.','State the uncertainty, gather proportionate qualitative and quantitative evidence, and define escalation.','Allow the most senior person to decide without documenting assumptions.'],c:2,r:'Evidence-conscious decisions do not confuse uncertainty with irrelevance or manufacture precision.'}
]
const questionsEs=[
 {id:'Q-001',title:'¿Sostenibilidad o ESG?',q:'Una organización publica indicadores de plantilla y emisiones, pero no tiene ningún proceso para utilizarlos en las decisiones. ¿Qué afirmación es más precisa?',a:['Publicar datos ESG demuestra que el modelo de negocio es sostenible.','El reporte ESG y la sostenibilidad son lo mismo.','Los indicadores pueden apoyar la rendición de cuentas ESG, pero su publicación por sí sola no demuestra un rendimiento sostenible.','Los indicadores carecen de valor salvo que todos los efectos se conviertan en dinero.'],c:2,r:'Los datos pueden apoyar la transparencia y la toma de decisiones, pero su valor depende del alcance, la calidad, la interpretación y la acción.'},
 {id:'Q-002',title:'Dimensiones conectadas',q:'Un equipo cambia a un proveedor de minerales de menor coste. La nueva fuente presenta impactos inciertos sobre el agua, informes sobre comisiones de contratación y una aprobación poco clara de proveedores de niveles inferiores. ¿Cuál es la mejor primera respuesta?',a:['Clasificarlo únicamente como un problema ambiental porque los minerales proceden de la naturaleza.','Clasificarlo únicamente como un problema social porque las comisiones de contratación afectan a trabajadores.','Tratarlo como una decisión conectada E/S/G e investigar la evidencia material antes de aprobarla.','Ignorar ESG porque el proveedor cumple la especificación del componente.'],c:2,r:'Los impactos sobre agua y materiales, las condiciones de los trabajadores y los controles de aprobación y evidencia están conectados.'},
 {id:'Q-003',title:'Externalidad y consecuencia',q:'¿Qué ejemplo demuestra mejor cómo una externalidad puede convertirse en una consecuencia empresarial?',a:['La contaminación afecta a una comunidad y provoca restricciones operativas, costes de reparación y pérdida de confianza.','Una orden de compra registra el precio unitario acordado.','Un responsable aprueba un presupuesto dentro de su autoridad delegada.','Un componente supera la inspección especificada.'],c:0,r:'Una consecuencia inicialmente externa a la transacción vuelve a través de restricciones, costes y respuesta de las partes interesadas.'},
 {id:'Q-004',title:'Gobernanza',q:'¿Qué evidencia indica con mayor solidez que un compromiso ESG público está gobernado y no es solo una declaración?',a:['El compromiso utiliza un lenguaje ambicioso.','Tiene un alcance definido, una persona responsable, recursos, medidas, controles y una vía de revisión.','Aparece de forma destacada en comunicaciones externas.','Un proveedor de calificaciones lo ha mencionado.'],c:1,r:'La gobernanza conecta la intención con la autoridad, la evidencia, la acción y la rendición de cuentas.'},
 {id:'Q-005',title:'Calidad de la decisión',q:'Un equipo no puede cuantificar con precisión un posible impacto sobre una comunidad. ¿Cuál es la actuación más defendible?',a:['Excluirlo porque solo la evidencia numérica es válida.','Inventar una cifra conservadora para completar la matriz.','Declarar la incertidumbre, recopilar evidencia cualitativa y cuantitativa proporcionada y definir el escalado.','Permitir que la persona de mayor rango decida sin documentar los supuestos.'],c:2,r:'Las decisiones basadas en evidencia no confunden incertidumbre con irrelevancia ni fabrican precisión.'}
]
export default function Assessment(){
 const {progress,saveQuestion}=useProgress(); const {lang}=useLanguage(); const es=lang==='es'; const questions=es?questionsEs:questionsEn
 const [index,setIndex]=useState(0); const [choice,setChoice]=useState(null)
 const q=questions[index],saved=progress.questions[q.id]; const [result,setResult]=useState(saved||null)
 const submit=e=>{e.preventDefault();if(choice===null)return;const n=resolveAttempt(result,choice,q.c);const full={...n,module:'00'};setResult(full);saveQuestion(q.id,full)}
 const change=i=>{setIndex(i);setChoice(null);setResult(progress.questions[questions[i].id]||null)}
 return <section className="assessment" aria-labelledby="check-title"><div className="eyebrow">{es?'COMPROBACIÓN DE CONOCIMIENTOS':'KNOWLEDGE CHECK'} · {index+1} / 5</div><h2 id="check-title">{q.title}</h2><p className="question">{q.q}</p>
  <form onSubmit={submit}><fieldset disabled={result?.completed}><legend className="sr-only">{es?'Elige una respuesta':'Choose one answer'}</legend>{q.a.map((a,i)=><label className={'answer '+(result?.reveal&&i===q.c?'correct':'')} key={a}><input type="radio" name={q.id} checked={choice===i} onChange={()=>setChoice(i)}/><span><b>{String.fromCharCode(65+i)}</b>{a}</span></label>)}</fieldset>
  {!result?.completed&&<button className="button primary" disabled={choice===null}>{es?'Enviar respuesta':'Submit response'}</button>}</form>
  {result&&<div tabIndex="-1" className={'feedback '+(result.correct?'positive':'caution')}><strong>{result.correct?(es?'Evidencia alineada':'Evidence aligned'):(es?'Revisa el razonamiento':'Review the reasoning')}</strong><p>{result.correct?q.r:result.reveal?(es?'La respuesta correcta es ':'The correct response is ')+String.fromCharCode(65+q.c)+'. '+q.r:(es?'Esta respuesta no recoge una parte del contexto de decisión. Revisa las opciones e inténtalo una vez más.':'This response misses part of the decision context. Review the options and try once more.')}</p>{!result.completed&&<button className="text-button" onClick={()=>{setChoice(null);setResult(result)}}>{es?'Reintentar pregunta':'Retry question'}</button>}</div>}
  <div className="question-nav" aria-label={es?'Navegación de preguntas':'Question navigation'}>{questions.map((x,i)=><button key={x.id} className={(i===index?'current ':'')+(progress.questions[x.id]?.completed?'done':'')} onClick={()=>change(i)} aria-label={(es?'Pregunta ':'Question ')+(i+1)}>{i+1}</button>)}</div>
 </section>
}
