import { useLanguage } from '../i18n/LanguageContext'
const Node=({title,detail,tone})=><div className={'diagram-node '+tone}><strong>{title}</strong><span>{detail}</span></div>
export function ConnectedESG(){
 const {lang}=useLanguage(); const es=lang==='es'
 return <figure className="diagram" aria-labelledby="esg-title"><figcaption><span>{es?'VISUAL 01':'VISUAL 01'}</span><h3 id="esg-title">{es?'Tres dimensiones, un único sistema de decisión':'Three dimensions, one decision system'}</h3></figcaption>
  <div className="orbit-system"><div className="orbit-core">{es?'DECISIÓN':'DECISION'}<small>{es?'evidencia · autoridad · consecuencia':'evidence · authority · consequence'}</small></div><Node tone="e" title={es?'AMBIENTAL':'ENVIRONMENTAL'} detail={es?'Dependencias · impactos · recursos':'Dependencies · impacts · resources'}/><Node tone="s" title={es?'SOCIAL':'SOCIAL'} detail={es?'Personas · derechos · relaciones':'People · rights · relationships'}/><Node tone="g" title={es?'GOBERNANZA':'GOVERNANCE'} detail={es?'Autoridad · controles · rendición de cuentas':'Authority · controls · accountability'}/></div>
  <details><summary>{es?'Alternativa textual':'Text alternative'}</summary><p>{es?'La información ambiental, social y de gobernanza converge en una decisión. La gobernanza determina cómo se evalúa la evidencia, cómo se asigna la autoridad y cómo se supervisan las consecuencias; ninguna de las tres dimensiones funciona de forma aislada.':'Environmental, social and governance information converges on a decision. Governance determines how evidence is evaluated, authority is assigned and consequences are monitored; none of the three dimensions operates in isolation.'}</p></details></figure>
}
export function GovernanceCascade(){
 const {lang}=useLanguage(); const es=lang==='es'
 const items=es?[['Supervisión débil','Las señales de advertencia se filtran'],['Evidencia distorsionada','Quienes deciden reciben una imagen incompleta'],['Mala decisión','Se pasan por alto restricciones y personas afectadas'],['Consecuencias','Los efectos operativos, sociales y financieros se acumulan']]:[['Weak oversight','Warning signals are filtered'],['Distorted evidence','Decision-makers receive an incomplete picture'],['Poor decision','Constraints and affected people are missed'],['Consequences','Operational, social and financial effects compound']]
 return <figure className="diagram"><figcaption><span>VISUAL 03</span><h3>{es?'Cascada de fallos de gobernanza':'Governance failure cascade'}</h3></figcaption><div className="flow">{items.map((x,i)=><Node key={x[0]} tone={'step s'+i} title={(i+1).toString().padStart(2,'0')+' · '+x[0]} detail={x[1]}/>)}</div><details><summary>{es?'Alternativa textual':'Text alternative'}</summary><ol>{items.map(x=><li key={x[0]}><strong>{x[0]}:</strong> {x[1]}</li>)}</ol></details></figure>
}
export function SliceDiagram({type}){
 const {lang}=useLanguage(); const es=lang==='es'
 const data=type==='environment'?(es?['Señal climática','Exposición operativa','Vulnerabilidad','Consecuencia empresarial','Control de adaptación']:['Climate signal','Operational exposure','Vulnerability','Business consequence','Adaptation control']):type==='social'?(es?['Organización','Proveedor de nivel 1','Reclutador / contratista','Trabajadores y comunidades','Vías de evidencia y reclamación']:['Organization','Tier 1 supplier','Recruiter / contractor','Workers and communities','Evidence and grievance routes']):(es?['Objetivo','Riesgo','Control','Evidencia operativa','Revisión y escalado']:['Objective','Risk','Control','Operating evidence','Review and escalation'])
 const title=type==='environment'?(es?'Ruta de riesgo climático':'Climate risk pathway'):type==='social'?(es?'Red de riesgo multinivel':'Multi-tier risk network'):(es?'Cadena de gobernanza':'Governance chain')
 return <figure className="diagram compact"><figcaption><span>{type.toUpperCase()} SYSTEM</span><h3>{title}</h3></figcaption><div className="flow">{data.map((x,i)=><Node key={x} tone="step" title={x} detail={i<data.length-1?(es?'Conecta con la siguiente capa de decisión':'Connects to the next decision layer'):(es?'Requiere seguimiento con responsable definido':'Requires accountable follow-through')}/>)}</div><details><summary>{es?'Alternativa textual':'Text alternative'}</summary><p>{data.join(' → ')}.</p></details></figure>
}
