import { useState } from 'react'
import { useProgress } from '../state/ProgressContext'
import { useLanguage } from '../i18n/LanguageContext'
const signalsEn=['Limited sub-tier evidence','Lowest price','Short lead time','Material traceability','Workforce information','Control ownership']
const signalsEs=['Evidencia limitada de niveles inferiores','Precio más bajo','Plazo de entrega corto','Trazabilidad de materiales','Información de la plantilla','Responsabilidad sobre los controles']
export default function ESGCompass(){
 const {progress,completeActivity}=useProgress(); const {lang}=useLanguage(); const es=lang==='es'; const signals=es?signalsEs:signalsEn
 const [selected,setSelected]=useState([]); const [recommendation,setRecommendation]=useState(''); const done=progress.activities['00']
 const toggle=x=>setSelected(s=>s.includes(x)?s.filter(y=>y!==x):[...s,x])
 const submit=e=>{e.preventDefault();if(selected.length>=4&&recommendation)completeActivity('00')}
 return <section className="activity-panel"><div className="eyebrow">{es?'ACTIVIDAD INTERACTIVA · ESG COMPASS':'INTERACTIVE ACTIVITY · ESG COMPASS'}</div><h2>{es?'Construye el mapa de decisión':'Build the decision map'}</h2><p>{es?'Compara evidencias desde las perspectivas ambiental, social, de gobernanza y operativa antes de elegir una vía. Este escenario de aprendizaje es ficticio y no representa una decisión real sobre proveedores.':'Compare evidence across environmental, social, governance and operational lenses before choosing a path. This fictional learning scenario is not an actual supplier decision.'}</p>
 <form onSubmit={submit}><fieldset><legend>{es?'Selecciona al menos cuatro señales que deban conectarse':'Select at least four signals that require connection'}</legend><div className="signal-grid">{signals.map(x=><label className="signal" key={x}><input type="checkbox" checked={selected.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span></label>)}</div></fieldset>
 <label className="select-label">{es?'Recomendación inicial':'Initial recommendation'}<select value={recommendation} onChange={e=>setRecommendation(e.target.value)}><option value="">{es?'Selecciona una vía condicionada':'Select a conditional path'}</option><option value="north">{es?'Elegir North con condiciones sobre la evidencia':'Choose North with evidence conditions'}</option><option value="east">{es?'Elegir East con condiciones de seguimiento':'Choose East with monitoring conditions'}</option><option value="current">{es?'Mantener el proveedor actual con un plan correctivo':'Retain current supplier with corrective plan'}</option><option value="defer">{es?'Aplazar y escalar la incertidumbre material':'Defer and escalate material uncertainty'}</option></select></label>
 <button className="button primary" disabled={selected.length<4||!recommendation}>{es?'Evaluar el mapa de decisión':'Evaluate decision map'}</button></form>
 {done&&<div className="feedback positive"><strong>{es?'Razonamiento conectado establecido':'Connected reasoning established'}</strong><p>{es?'Una recomendación defendible identifica el objetivo, la evidencia, la incertidumbre, las condiciones y la persona responsable. Distintas vías pueden ser razonables cuando se respetan los requisitos no negociables.':'A defensible recommendation states the objective, evidence, uncertainty, conditions and accountable owner. Different paths may be reasonable when non-negotiable requirements are respected.'}</p></div>}</section>
}
