import { useState } from 'react'
import Markdown from './Markdown'
import { useProgress } from '../state/ProgressContext'
import { useLanguage } from '../i18n/LanguageContext'

export default function ReasoningActivity({content}){
 const {progress,completeActivity}=useProgress(); const {lang}=useLanguage(); const es=lang==='es'
 const evidence=es?['Límite y partes afectadas','Calidad de datos e incertidumbre','Impacto, dependencia o riesgo sobre derechos','Autoridad, controles y escalado']:['Boundary and affected parties','Data quality and uncertainty','Impact, dependency or rights risk','Authority, controls and escalation']
 const prior=progress.activities[content.id]; const [ratings,setRatings]=useState(prior?.ratings||{}); const [decision,setDecision]=useState(prior?.decision||''); const [condition,setCondition]=useState(prior?.condition||'')
 const classified=Object.keys(ratings).length, ready=classified===4&&decision&&condition.trim().length>=20
 const submit=e=>{e.preventDefault();if(ready)completeActivity(content.id,{ratings,decision,condition,completed:true})}
 return <div className="activity-production"><div className="activity-brief"><div className="eyebrow">{es?'RAZONAMIENTO APLICADO':'APPLIED REASONING'}</div><h2>{content.activityTitle}</h2><Markdown source={content.activity}/></div>
  <form className="evidence-workbench" onSubmit={submit}><h3>{es?'Construye tu registro de decisión':'Build your decision record'}</h3><p>{es?'Clasifica cada línea de evidencia. No existe un atajo de puntuación única: tu recomendación debe conservar una condición.':'Classify every evidence line. There is no single-score shortcut: your recommendation must retain a condition.'}</p>
   {evidence.map((item,i)=><label className="evidence-row" key={item}><span><b>0{i+1}</b>{item}</span><select value={ratings[i]||''} onChange={e=>setRatings({...ratings,[i]:e.target.value})}><option value="">{es?'Clasificar evidencia…':'Classify evidence…'}</option><option value="Established">{es?'Establecida':'Established'}</option><option value="Partial / uncertain">{es?'Parcial / incierta':'Partial / uncertain'}</option><option value="Material gap">{es?'Laguna material':'Material gap'}</option><option value="Requires escalation">{es?'Requiere escalado':'Requires escalation'}</option></select></label>)}
   <label className="field-label">{es?'Decisión':'Decision'}<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="">{es?'Elige una respuesta gobernada…':'Choose a governed response…'}</option><option value="Proceed with controls">{es?'Continuar con controles':'Proceed with controls'}</option><option value="Proceed conditionally">{es?'Continuar de forma condicional':'Proceed conditionally'}</option><option value="Pause and investigate">{es?'Pausar e investigar':'Pause and investigate'}</option><option value="Escalate before approval">{es?'Escalar antes de aprobar':'Escalate before approval'}</option></select></label>
   <label className="field-label">{es?'Condición de evidencia':'Evidence condition'}<textarea value={condition} onChange={e=>setCondition(e.target.value)} placeholder={es?'Indica qué debe verificarse, por quién y cuándo debe revisarse.':'State what must be verified, by whom, and when it must be reviewed.'}/></label>
   <button className="button primary" disabled={!ready}>{prior?(es?'Actualizar registro de decisión':'Update decision record'):(es?'Completar actividad':'Complete activity')}</button>{!ready&&<small>{es?'Clasifica las cuatro líneas, elige una decisión y escribe una condición de al menos 20 caracteres.':'Classify all four lines, choose a decision and write a condition of at least 20 characters.'}</small>}
   {prior&&<div className="feedback positive"><strong>{es?'Registro de decisión guardado':'Decision record saved'}</strong><p>{es?'Tus clasificaciones de evidencia y la condición explícita forman parte del registro de finalización de este módulo.':'Your evidence classifications and explicit condition are part of this module’s completion record.'}</p></div>}
  </form></div>
}
